use_frameworks!

platform :ios, '9.0'
target 'mixpanelFlutter_Example' do
  pod 'mixpanelFlutter', :path => '../'
#  warn_for_unused_master_specs_repo => false

  target 'mixpanelFlutter_Tests' do
    inherit! :search_paths

    
  end
end
